"""Plot attention entropy vs hidden-state mismatch per layer.

Input:
  JSON file produced by run_experiment.py at <output_dir>/step_metrics.json

Output:
  One scatter plot per layer:
    x-axis: attention entropy
    y-axis: hidden mismatch (default: hidden_l2)
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

import numpy as np


def load_step_metrics(path: Path) -> list[dict]:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError(f"Expected list in {path}, got {type(data).__name__}")
    return data


def pearson_corr(x: np.ndarray, y: np.ndarray) -> float:
    if x.size < 2 or y.size < 2:
        return float("nan")
    if np.allclose(x.std(), 0.0) or np.allclose(y.std(), 0.0):
        return float("nan")
    return float(np.corrcoef(x, y)[0, 1])


def scatter_per_layer(
    records: list[dict],
    output_dir: Path,
    diff_key: str = "hidden_l2",
    alpha: float = 0.35,
):
    import matplotlib.pyplot as plt

    by_layer: dict[int, list[dict]] = defaultdict(list)
    for row in records:
        if "layer" not in row:
            continue
        if "attn_entropy" not in row or diff_key not in row:
            continue
        by_layer[int(row["layer"])].append(row)

    if not by_layer:
        raise ValueError("No valid rows found for plotting.")

    output_dir.mkdir(parents=True, exist_ok=True)

    for layer in sorted(by_layer.keys()):
        rows = by_layer[layer]
        x = np.array([float(r["attn_entropy"]) for r in rows], dtype=np.float64)
        y = np.array([float(r[diff_key]) for r in rows], dtype=np.float64)

        fig, ax = plt.subplots(figsize=(6, 4.5), dpi=140)
        ax.scatter(x, y, s=12, alpha=alpha, edgecolors="none")

        # Linear trend line to show direction.
        if x.size >= 2 and not np.allclose(x.std(), 0.0):
            coeff = np.polyfit(x, y, deg=1)
            xx = np.linspace(x.min(), x.max(), 100)
            yy = coeff[0] * xx + coeff[1]
            ax.plot(xx, yy, linewidth=1.5)

        corr = pearson_corr(x, y)
        corr_text = "nan" if np.isnan(corr) else f"{corr:.4f}"
        ax.set_title(f"Layer {layer}: entropy vs {diff_key} (r={corr_text})")
        ax.set_xlabel("attention entropy")
        ax.set_ylabel(diff_key)
        ax.grid(True, alpha=0.2)

        out_file = output_dir / f"layer_{layer:02d}_entropy_vs_{diff_key}.png"
        fig.tight_layout()
        fig.savefig(out_file)
        plt.close(fig)
        print(f"[saved] {out_file}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot per-layer scatter: x=attention entropy, y=hidden mismatch."
    )
    parser.add_argument(
        "--input",
        default="outputs/step_metrics.json",
        help="Path to step_metrics.json generated by run_experiment.py",
    )
    parser.add_argument(
        "--output-dir",
        default="outputs/plots",
        help="Directory to save per-layer scatter plots",
    )
    parser.add_argument(
        "--diff-key",
        default="hidden_l2",
        choices=["hidden_l2", "hidden_rel_l2", "hidden_cosine_distance"],
        help="Which hidden mismatch metric to use as y-axis",
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.35,
        help="Point transparency for scatter",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    input_path = Path(args.input)
    output_dir = Path(args.output_dir)

    records = load_step_metrics(input_path)
    scatter_per_layer(
        records=records,
        output_dir=output_dir,
        diff_key=args.diff_key,
        alpha=args.alpha,
    )


if __name__ == "__main__":
    main()
